export const datalist = [
    {
        condition: '(Reto) Haga 10 lagartijas',
        action: 'Si lo logra reparte 4 tragos si no se toma los 4',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Deje la persona de la derecha le de una nalgada fuerte',
        action: 'Si acepta reparte 6 tragos si no se toma 5',
        type: '',
        answer: '',
    },
     
    {
        condition: '(Reto) Fondéese lo que está tomando',
        action: 'Si lo hace reparte 2 shots si no se toma 1',
        type: '',
        answer: '',
    },
    
    {
        condition: '(Reto) Enseñe la galeria de fotos de su telefono en la parte de escondidos',
        action: 'Si lo hace reparte 1 shot si no se toma 1',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) El/La que mando nudes más recientemente',
        action: 'Reparte 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) El/La que haya hecho él sin respeto más recientemente',
        action: 'Reparte 5 tragos',
        type: '',
        answer: '',
    },
     
    {
        condition: '(Grupal) Los claretianos',
        action: 'Toman 1 shot',
        type: '',
        answer: '',
    },
    {
        condition: 'EL más roco',
        action: 'Toman 1 shot',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los manudos',
        action: 'Reparten 4 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los morados o heredianos',
        action: 'Toman 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los que estudian o estudiaron en la UCR',
        action: 'Toman 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los que estudian o estudiaron en la UNA',
        action: 'Reparten 4 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los que andan ropa interior roja',
        action: 'Reparten 3 tragos',
        type: '',
        answer: '',
    },
     
    {
        condition: 'El/La que esté más mamad@',
        action: 'Toma 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Juego) Cultura chupistica de posiciones sexuales',
        action: 'EL/La que pierde toma 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Propóngale matrimonio a la persona de la derecha, lo más convincente posible',
        action: 'Los demás deciden, si fue convincente reparte 5 tragos si no se toma 3',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Gire una botella como "Botellita" y al o la que caiga le da un beso en el cuello',
        action: 'Si lo hace reparte 2 shot si no se toma 1',
        type: 'Hot',
        answer: '',
    },
    {
        condition: '(Reto) Carta de suerte, tomese un trago de agua',
        action: 'No queremos vomitadas',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Carta de suerte, tomese un trago de agua',
        action: 'No queremos vomitadas',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Carta de suerte, tomese un trago de agua',
        action: 'No queremos vomitadas',
        type: '',
        answer: '',
    },
    {
        condition: '(Juego) Todos van a bajar la cabeza, cuentan hasta 3 y al mismo tiempo vuelven a ver a alguien. Juegan 3 rondas',
        action: 'Si 2 personas se ven a los ojos los 2 tomas 2 tragos',
        type: '',
        answer: '',
    },
    {
        condition: 'Verdad o reto',
        action: 'Si lo cumple o response reparte 4 tragos si no se toma 6',
        type: '',
        answer: '',
    },
    {
        condition: 'Verdad o reto',
        action: 'Si lo cumple o response reparte 4 tragos si no se toma 6',
        type: '',
        answer: '',
    }
]

export const titles = [
    "Pack de preguntas y retos #1",
    "Pack de preguntas y retos #2",
    "Pack de solo preguntas #1",
    "Pack de solo preguntas #2",
]


export const questions = [
    [  
        ...datalist,
        {
            condition: '(Pregunta individual / cultura general) ¿Quién escribió La Odisea?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Homero',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año cayó el muro de Berlín?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'En 1989',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Hace cuánto se extinguieron los dinosaurios?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Hace 66 millones de años',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué presidente de Estados Unidos fue asesinado en Dallas?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'John F. Kennedy',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿A cuántos kilómetros equivale una milla?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: '1.6 km',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué es más grande un átomo o una célula?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Una célula',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el animal más grande de la Tierra?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'La ballena azul',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántas películas de "Harry Potter" se han hecho?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Ocho',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién pintó “la última cena”?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Leonardo da Vinci',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué año llegó Cristóbal Colón a América?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: '1492',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién ha protagonizado la saga de Indiana Jones?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Harrison Ford.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año murió Freddie Mercury?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: '1991',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuándo empezó la Primera Guerra Mundial?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'En 1914',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién es el padre del psicoanálisis?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Sigmund Freud',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el disco más vendido de la historia?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Thriller, de Michael Jackson. (Viva el hehe)',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué lugar del cuerpo se produce la insulina?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'En el páncreas es donde se produce la insulina.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Con qué se fabricaba el pergamino?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'El pergamino se fabrica con los piel de animales',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Dónde está la Casa Blanca?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Washington D.C.',
        },
        {
            condition: '(Pregunta individual / cultura general) Que presidente de la República que abolió la pena de muerte?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Tomás Guardia',
        },
        {
            condition: '(Pregunta individual / cultura general) Cual fue el primer presidente de la República de Costa Rica?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'José M Castro Madriz',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el país más pequeño del mundo?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Vaticano',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántos océanos hay en la Tierra?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: '5',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el río más largo del mundo?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question1',
            answer: 'Nilo',
        }
    ],
    [
        ...datalist,
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año se aprobó la actual Constitución española?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'En 1978',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál fue el primer presidente democrático de España tras la dictadura franquista?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Adolfo Suárez',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué día es la fiesta nacional de Estados Unidos?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'El 4 de julio',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién inventó la bombilla?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Thomas Edison',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año se produjo la Revolución Francesa?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'En 1789',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Dónde se encuentra la Sagrada Familia?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'En Barcelona',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el océano más grande del mundo?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'El océano Pacífico',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el país más grande del mundo?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Rusia, con 17.075.200 km² de superficie',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es la ciudad de los rascacielos?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Nueva York',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué país del mundo produce más vino?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Italia',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántos huesos hay en el cuerpo humano?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Un adulto tiene 206 huesos',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llama el proceso por el cual las plantas se alimentan?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Fotosíntesis',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuánto vale el número pi con 4 decimales?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: '3.1416',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué elemento de la tabla periódica tiene como símbolo He?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Helio',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué planeta es el que se encuentra más cercano al Sol?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Mercurio',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién dirigió "Origen" (Inception)?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Christopher Nolan',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Por qué película ganó Leonardo DiCaprio su primer Óscar?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'El Renacido',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es la película con más Óscars de la historia?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: "Titanic', 'Ben-Hur' y el 'Señor de los anillos: El retorno del rey' (11 estatuillas).",
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál fue la primera película de Disney?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: "'Blancanieves y los siete enanitos' (1937)",
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es la película más taquillera de la historia?',
            action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
            type: 'Question2',
            answer: 'Avatar',
        },
    ],
    [
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál fue la primera película de terror en color?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'La maldición de Frankenstein',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántas películas hay de Saw?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Nueve',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién interpretó a Hermione Granger en Harry Potter?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Emma Watson',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué ciudad se ambiente Cazafantasmas?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'En Nueva York',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿A qué saga pertenece el personaje de Katniss Everdeen?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: "A 'Los Juegos del Hambre'",
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llama la casa de los Weasley en Harry Potter?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'La Madriguera.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿A qué mítica actriz interpreta Ana de Armas en Blonde?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Marilyn Monroe.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llama la mujer de Shrek?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Fiona.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántos lados tiene un heptadecágono?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Diecisete.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿De dónde sale el aceite de oliva?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'De las aceitunas.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llama el satélite más grande de Saturno?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Titán.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el único mamífero capaz de volar?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: ' El murciélago.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántos corazones tiene un pulpo?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Tres.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llama el triángulo que tiene sus tres lados iguales?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Equilátero.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el órgano más grande del cuerpo humano?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'La piel.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el animal que más muertes provoca cada año?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'El mosquito.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Dónde se inventó la pizza?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'En Nápoles.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el río más largo de Europa?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'El Volga.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Dónde se encuentra el museo del Louvre?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'En París.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llama el río más famoso de Egipto?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'El Nilo.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué país se encuentra el rascacielos más alto del mundo?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'En Dubai.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el país más poblado de África?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Nigeria.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿De qué país es originario el café?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'De Etiopía.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué dos países separa el estrecho de Bering?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Rusia y Estados Unidos.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué país nació Adolf Hitler?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Austria.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuánto duró “La Guerra de los Cien Años”?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: '116 años.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién fue el último faraón de Egipto?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Ramsés III.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál fue la primera civilización humana?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'La civilización sumeria.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál fue el genocidio más grande de la historia?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'El Holocausto.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuándo empezó la Revolución Rusa?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'En 1917.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién creó el Partido Comunista?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Lenin.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué famoso líder de Cuba estuvo 49 años en el poder? ',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question3',
            answer: 'Fidel Castro',
        },
        
    ],
    [
        {
            condition: '(Pregunta individual / cultura general) ¿Cuándo se fundó la OTAN?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'En 1949',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año fue asesinado Abraham Lincoln?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'En 1865.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año se hundió el Titanic?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'En 1912.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál fue el primer metal que el hombre empleó?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'El cobre.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué personaje fue conocido como el rey de Macedonia?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Alejandro Magno.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué continente surgió la Humanidad?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'En África.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué año cayó el Imperio Romano?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'En el año 476.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿A qué país pertenece Groenlandia?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Dinamarca.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es la moneda oficial de Japón?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'El yen.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál era la ciudad más cercana a la central nuclear de Chernóbil?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Prípiat.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Dónde está Transilvania?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'En Rumanía.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el estado más grande Estados Unidos?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Alaska.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es la capital de Nicaragua?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Maragua.',
        },
        {
            condition: '(Pregunta individual / cultura general) Nombra un país que no tenga río.',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Ciudad del Vaticano.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Es más grande Canadá o Estados Unidos?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Canadá.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién fue el primer emperador romano?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'César Augusto.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el mineral más duro del planeta? ',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'El diamante.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuál es el animal más rápido del mundo?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: ' El guepardo.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuáles son los cinco tipos de sabores primarios?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Dulce, amargo, ácido, salado y umami.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué órgano del cuerpo consume más energía?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'El cerebro.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuántos dientes tiene un humano adulto?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: '32.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué descubrieron Marie Curie y su esposo Pierre?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'La radioactividad.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué gas liberan las plantas al hacer la fotosíntesis?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Oxígeno.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cuáles son los tres colores primarios?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'El amarillo, el azul y el rojo.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién interpretó a Eduardo Manostijeras?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Johnny Depp.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Quién protagonizó la película Gladiator?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Russell Crowe.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué actor interpreta al personaje de Thor en el Universo Cinematográfico de Marvel?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: ' Chris Hemsworth.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿En qué país nació la actriz Margot Robbie?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Australia.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Cómo se llamaba el lobo de Jon Nieve?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Fantasma.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿Qué familia vive en la ciudad de Springfield?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Los Simpsons.',
        },
        {
            condition: '(Pregunta individual / cultura general) ¿De qué serie es popular el personaje de Michael Scofield?',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: ' ‘Prison Break’.',
        },
        {
            condition: '(Pregunta individual / cultura general) Nombra a los personajes principales de ‘Friends’.',
            action: 'Si responde bien, reparte 1 shot, si no se lo toma',
            type: 'Question4',
            answer: 'Ross, Rachel, Joey, Chandler, Monica y Phoebe.',
        },
    ]
]
