export const datalist = [
    {
        condition: '(Reto) Haga 10 lagartijas',
        action: 'Si lo logra reparte 4 tragos si no se toma los 4',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Deje la persona de la derecha le de una nalgada fuerte',
        action: 'Si acepta reparte 6 tragos si no se toma 5',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Fondéese lo que está tomando',
        action: 'Si lo hace reparte 2 shots si no se toma 1',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Enseñe la galeria de fotos de su telefono en la parte de escondidos',
        action: 'Si lo hace reparte 1 shot si no se toma 1',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) El/La que mando nudes más recientemente',
        action: 'Reparte 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) El/La que haya hecho él sin respeto más recientemente',
        action: 'Reparte 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los claretianos',
        action: 'Toman 1 shot',
        type: '',
        answer: '',
    },
    {
        condition: 'EL más roco',
        action: 'Toman 1 shot',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los manudos',
        action: 'Reparten 4 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los morados o heredianos',
        action: 'Toman 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los que estudian o estudiaron en la UCR',
        action: 'Toman 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los que estudian o estudiaron en la UNA',
        action: 'Reparten 4 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Grupal) Los que andan ropa interior roja',
        action: 'Reparten 3 tragos',
        type: '',
        answer: '',
    },
    {
        condition: 'El/La que esté más mamad@',
        action: 'Toma 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Juego) Cultura chupistica de posiciones sexuales',
        action: 'EL/La que pierde toma 5 tragos',
        type: '',
        answer: '',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Quién escribió La Odisea?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Homero',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Quién pintó “la última cena”?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Leonardo da Vinci',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Qué año llegó Cristóbal Colón a América?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: '1492',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Quién ha protagonizado la saga de Indiana Jones?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Harrison Ford.',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿En qué año murió Freddie Mercury?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: '1991',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Cuándo empezó la Primera Guerra Mundial?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'En 1914',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Quién es el padre del psicoanálisis?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Sigmund Freud',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Cuál es el disco más vendido de la historia?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Thriller, de Michael Jackson. (Viva el hehe)',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿En qué lugar del cuerpo se produce la insulina?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'En el páncreas es donde se produce la insulina.',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Con qué se fabricaba el pergamino?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'El pergamino se fabrica con los piel de animales',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Dónde está la Casa Blanca?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Washington D.C.',
    },
    {
        condition: '(Reto) Propóngale matrimonio a la persona de la derecha, lo más convincente posible',
        action: 'Los demás deciden, si fue convincente reparte 5 tragos si no se toma 3',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Gire una botella como "Botellita" y al o la que caiga le da un beso en el cuello',
        action: 'Si lo hace reparte 2 shot si no se toma 1',
        type: 'Hot',
        answer: '',
    },
    {
        condition: '(Reto) Carta de suerte, tomese un trago de agua',
        action: 'No queremos vomitadas',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Carta de suerte, tomese un trago de agua',
        action: 'No queremos vomitadas',
        type: '',
        answer: '',
    },
    {
        condition: '(Reto) Carta de suerte, tomese un trago de agua',
        action: 'No queremos vomitadas',
        type: '',
        answer: '',
    },
    {
        condition: '(Juego) Todos van a bajar la cabeza, cuentan hasta 3 y al mismo tiempo vuelven a ver a alguien. Juegan 3 rondas',
        action: 'Si 2 personas se ven a los ojos los 2 tomas 2 tragos',
        type: '',
        answer: '',
    },
    {
        condition: 'Verdad o reto',
        action: 'Si lo cumple o response reparte 4 tragos si no se toma 6',
        type: '',
        answer: '',
    },
    {
        condition: 'Verdad o reto',
        action: 'Si lo cumple o response reparte 4 tragos si no se toma 6',
        type: '',
        answer: '',
    },
    {
        condition: '(Pregunta individual / cultura general) Que presidente de la República que abolió la pena de muerte?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Tomás Guardia',
    },
    {
        condition: '(Pregunta individual / cultura general) Cual fue el primer presidente de la República de Costa Rica?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'José M Castro Madriz',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Cuál es el país más pequeño del mundo?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Vaticano',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Cuántos océanos hay en la Tierra?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: '5',
    },
    {
        condition: '(Pregunta individual / cultura general) ¿Cuál es el río más largo del mundo?',
        action: 'Si responde bien, reparte 4 tragos, si no se toma 4',
        type: 'Question',
        answer: 'Nilo',
    },
    

]

